# Site settings
title: "Strohland"
email: strohland@outlook.com
description: ""
baseurl: ""
url: "http://haberstrohr.github.io"
title_description: ""
title_image: "/img/avatar.jpg"
google_analytics: ""
disqus_account: strohland
github_repository: https://github.com/haberstrohr
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: strohland
github_username:  haberstrohr
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: ""
footer_right: "&lt;/&gt; on <a href=\"https://github.com/haberstrohr/haberstrohr.github.io\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
